account/urls.py
from django.urls import path

app_name = 'account'


urlpatterns = [
    
]

blog/urls.py
from django.urls import path
from .views import (
    blog_list,
    blog_detail
)

app_name = 'blog'

urlpatterns = [
    path('list/', blog_list, name='list'),
    path('detail/<slug:slug>/', blog_detail, name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('room/', include('room.urls', namespace='room')),

]

main/urls.py
from django.urls import path
from main.views import (
    home_view,
    about_view,
    contact_view,
)

app_name = 'main'

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact')
]

room/urls.py
from django.urls import path
from .views import (
    room_list,
    room_detail
)

app_name = 'room'

urlpatterns = [
    path('list/', room_list, name='list'),
    path('detail/', room_detail, name='detail')
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.utils import timezone


class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='media/blogs', blank=True, null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(editable=False, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)


class BlogContent(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.TextField()
    is_quote = models.BooleanField(default=False)


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='parent')
    top_level_comment = models.IntegerField(null=True, blank=True)

    @property
    def children(instance, *args, **kwargs):
        if not instance.top_level_comment:
            child = Comment.objects.filter(top_level_comment=instance.id).order_by('-id')
            return child
        else:
            return None

    def __str__(self):
        return self.blog


def comment_pre_save(sender, instance, *args, **kwargs):
    if instance.parent_comment:
        if instance.parent_comment.top_level_comment:
            instance.top_level_comment = instance.parent_comment.top_level_comment
        else:
            instance.top_level_comment = instance.parent_comment.id


def article_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title + "-" + str(timezone.now().date()))


pre_save.connect(article_pre_save, sender=Blog)
pre_save.connect(comment_pre_save, sender=Comment)

main/models.py
from django.db import models

room/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.utils import timezone


class RoomServices(models.Model):
    images = models.ImageField(null=True, blank=True, upload_to='media/room_services')
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


# class BookRoom(models.Model):
    # check_in = models.DateTimeField(default=timezone.now)
    # check_out = models.DateTimeField(default=timezone.now)
    # pass


class Room(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(editable=False, null=True, blank=True)
    price = models.DecimalField(max_digits=550, decimal_places=5)
    size = models.PositiveSmallIntegerField(default=1)
    capacity = models.PositiveSmallIntegerField(default=1)
    bed = models.CharField(max_length=255)
    services = models.ManyToManyField(RoomServices)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class RoomImages(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True, blank=True, related_name='images')
    image = models.ImageField(null=True, blank=True, upload_to='media/room_image')
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.room.title

    def get_image(self):
        if self.image:
            return mark_safe(
                f'<a href="{self.image.url}" target="_blank"><img src="{self.image.url}" width="50" height="50" /></a>')
        return '-'


class RoomReview(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='review_room', null=True, blank=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='room_review_autor')
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)


class RoomContent(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='content_room')
    content = RichTextField()
    is_checked = models.BooleanField(default=False)

    def __str__(self):
        return self.room.title


def room_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title + "-")


pre_save.connect(room_pre_save, sender=Room)

account/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render
from .models import (
    Blog
)


def blog_list(request):
    ctx = {

    }
    return render(request, 'blog/blog.html', ctx)


def blog_detail(request, slug):
    blogs = Blog.objects.all(Blog, slug=slug)
    ctx = {
        'blogs': blogs
    }
    return render(request, 'blog/single-blog.html', ctx)

main/views.py
from django.shortcuts import render
from room.models import (
    Room,
    RoomImages
)


def home_view(request):
    rooms = Room.objects.all()
    images = RoomImages.objects.all()
    ctx = {
        'images': images,
        'rooms': rooms
    }
    return render(request, 'main/index.html', ctx)


def about_view(request):
    ctx = {

    }
    return render(request, 'main/about.html', ctx)


def contact_view(request):
    ctx = {

    }
    return render(request, 'main/contact.html', ctx)

room/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from room.models import (
    Room,
    RoomImages,
    RoomServices
)


def room_list(request):
    rooms = Room.objects.all()
    services = RoomServices.objects.all()
    images = RoomImages.objects.all()
    paginator = Paginator(rooms, 1)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    ctx = {
        'page_obj': page_obj,
        'services': services,
        'images': images
    }
    return render(request, 'room/room.html', ctx)


def room_detail(request):
    ctx = {

    }
    return render(request, 'room/single-room.html')

templates/main/about.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	

<div class="breadcrumb-area bg-img bg-overlay jarallax" style="background-image: url({% static 'img/bg-img/16.jpg' %});">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcrumb-content text-center">
                    <h2 class="page-title">About Us</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'main:home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">About Us</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="roberto-about-us-area section-padding-100-0">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg-6">
                <div class="about-thumbnail pr-lg-5 mb-100 wow fadeInUp" data-wow-delay="100ms">
                    <img src="{% static 'img/bg-img/19.jpg' %}" alt>
                </div>
            </div>
            <div class="col-12 col-lg-6">

                <div class="section-heading wow fadeInUp" data-wow-delay="300ms">
                    <h6>Testimonials</h6>
                    <h2>20 Years Of Experience</h2>
                </div>
                <div class="about-content mb-100 wow fadeInUp" data-wow-delay="500ms">
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia dese mollit anim id est
                        laborum. Sed ut perspiciatis unde omnis iste.</p>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia dese mollit anim id est
                        laborum. Sed ut perspiciatis unde omnis iste. Lorem Ipsum available.</p>
                    <img src="{% static 'img/core-img/signature.png' %}" alt>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="roberto--video--area bg-img bg-overlay jarallax section-padding-0-100"
     style="background-image: url({% static 'img/bg-img/20.jpg' %});">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center">
            <div class="col-12 col-md-6">

                <div class="section-heading text-center white wow fadeInUp" data-wow-delay="100ms">
                    <h6>Ultimate Solutions</h6>
                    <h2>Our Hotel &amp; Room</h2>
                </div>
                <div class="video-content-area mt-100 wow fadeInUp" data-wow-delay="500ms">
                    <a href="https://www.youtube.com/watch?v=Ldd8yjjo6jA" class="video-play-btn"><i
                            class="fa fa-play"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="roberto-service-area section-padding-100-0">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="section-heading text-center wow fadeInUp" data-wow-delay="100ms">
                    <h6>Ultimate Solutions</h6>
                    <h2>Our Hotel &amp; Room</h2>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-12 col-md-6 col-lg-4">
                <div class="single-service-area mb-100 wow fadeInUp" data-wow-delay="300ms">
                    <img src="{% static 'img/bg-img/21.jpg' %}" alt>
                    <div class="service-title d-flex align-items-center justify-content-center">
                        <h5>Restaurant &amp; Bar</h5>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-4">
                <div class="single-service-area mb-100 wow fadeInUp" data-wow-delay="500ms">
                    <img src="{% static 'img/bg-img/22.jpg' %}" alt>
                    <div class="service-title d-flex align-items-center justify-content-center">
                        <h5>Spa &amp; Fitness</h5>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-4">
                <div class="single-service-area mb-100 wow fadeInUp" data-wow-delay="700ms">
                    <img src="{% static 'img/bg-img/23.jpg' %}" alt>
                    <div class="service-title d-flex align-items-center justify-content-center">
                        <h5>Pool &amp; Party</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock %}

templates/main/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	

<div class="breadcrumb-area contact-breadcrumb bg-img bg-overlay jarallax"
     style="background-image: url({% static 'img/bg-img/18.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-content text-center mt-100">
                    <h2 class="page-title">Contact Us</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'main:home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="google-maps-contact-info">
    <div class="container-fluid">
        <div class="google-maps-contact-content">
            <div class="row">

                <div class="col-6 col-lg-3">
                    <div class="single-contact-info">
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        <h4>Phone</h4>
                        <p>+01-234-567-890</p>
                    </div>
                </div>

                <div class="col-6 col-lg-3">
                    <div class="single-contact-info">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <h4>Address</h4>
                        <p>Iris Watson, 283 Fusce Rd,NY</p>
                    </div>
                </div>

                <div class="col-6 col-lg-3">
                    <div class="single-contact-info">
                        <i class="fa fa-clock-o" aria-hidden="true"></i>
                        <h4>Open time</h4>
                        <p>10:00 am to 23:00 pm</p>
                    </div>
                </div>

                <div class="col-6 col-lg-3">
                    <div class="single-contact-info">
                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                        <h4>Email</h4>
                        <p>Info.colorlib @gmail.com</p>
                    </div>
                </div>
            </div>

            <div class="google-maps">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d119544.65384183972!2d69.18802003178008!3d41.355491637874636!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef3874b503727%3A0x87d7b3568c7badc8!2sFarobiy%20IT%20Academy!5e1!3m2!1sen!2s!4v1707997856547!5m2!1sen!2s" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
</section>


<div class="roberto-contact-form-area section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="section-heading text-center wow fadeInUp" data-wow-delay="100ms">
                    <h6>Contact Us</h6>
                    <h2>Leave Message</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">

                <div class="roberto-contact-form">
                    <form action="#" method="post">
                        <div class="row">
                            <div class="col-12 col-lg-6 wow fadeInUp" data-wow-delay="100ms">
                                <input type="text" name="message-name" class="form-control mb-30"
                                       placeholder="Your Name">
                            </div>
                            <div class="col-12 col-lg-6 wow fadeInUp" data-wow-delay="100ms">
                                <input type="email" name="message-email" class="form-control mb-30"
                                       placeholder="Your Email">
                            </div>
                            <div class="col-12 wow fadeInUp" data-wow-delay="100ms">
                                <textarea name="message" class="form-control mb-30"
                                          placeholder="Your Message"></textarea>
                            </div>
                            <div class="col-12 text-center wow fadeInUp" data-wow-delay="100ms">
                                <button type="submit" class="btn roberto-btn mt-15">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/navbar.html
{% load static %}
<div id="preloader">
    <div class="loader"></div>
</div>


<header class="header-area">

    <div class="search-form d-flex align-items-center">
        <div class="container">
            <form action="https://preview.colorlib.com/theme/roberto/index.html" method="get">
                <input type="search" name="search-form-input" id="searchFormInput" placeholder="Type your keyword ...">
                <button type="submit"><i class="icon_search"></i></button>
            </form>
        </div>
    </div>

    <div class="top-header-area">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="top-header-content">
                        <a href="#"><i class="icon_phone"></i> <span>(123) 456-789-1230</span></a>
                        <a href="#"><i class="icon_mail"></i> <span><span class="__cf_email__"
                                                                          data-cfemail="3b52555d541558545754495752597b5c565a525715585456">[email&#160;protected]</span></span></a>
                    </div>
                </div>
                <div class="col-6">
                    <div class="top-header-content">

                        <div class="top-social-area ml-auto">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-tripadvisor" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">

                <nav class="classy-navbar justify-content-between" id="robertoNav">

                    <a class="nav-brand" href="index-2.html"><img src="{% static 'img/core-img/logo.png' %}" alt></a>

                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <div class="classy-menu">

                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <div class="classynav">
                            <ul id="nav">
                                <li class="active"><a href="{% url 'main:home' %}">Home</a></li>
                                <li><a href="{% url 'room:list' %}">Rooms</a></li>
                                <li><a href="{% url 'main:about' %}">About Us</a></li>
                                <li><a href="#">Pages</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'main:home' %}">- Home</a></li>
                                        <li><a href="{% url 'room:list' %}">- Rooms</a></li>
                                        <li><a href="{% url 'room:detail' %}">- Single Rooms</a></li>
                                        <li><a href="{% url 'main:about' %}">- About Us</a></li>
                                        <li><a href="{% url 'blog:list' %}">- Blog</a></li>
{#                                        <li><a href="{% url 'blog:detail' %}">- Single Blog</a></li>#}
                                        <li><a href="{% url 'main:contact' %}">- Contact</a></li>
                                        <li><a href="#">- Dropdown</a>
                                            <ul class="dropdown">
                                                <li><a href="#">- Dropdown Item</a></li>
                                                <li><a href="#">- Dropdown Item</a></li>
                                                <li><a href="#">- Dropdown Item</a></li>
                                                <li><a href="#">- Dropdown Item</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'blog:list' %}">News</a></li>
                                <li><a href="{% url 'main:contact' %}">Contact</a></li>
                            </ul>

                            <div class="search-btn ml-4">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </div>

                            <div class="book-now-btn ml-3 ml-lg-5">
                                <a href="#">Book Now <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                            </div>
                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

templates/room/room.html
{% extends 'base.html' %}
{% load static %}


{% block content %}



    <div class="breadcrumb-area bg-img bg-overlay jarallax"
         style="background-image: url({% static 'img/bg-img/16.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcrumb-content text-center">
                        <h2 class="page-title">Our Room</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="{% url 'main:home' %}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Room</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="roberto-rooms-area section-padding-100-0">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-8">

                    {% for blogs in page_obj %}
                    	<div class="single-room-area d-flex align-items-center mb-50 wow fadeInUp" data-wow-delay="100ms">

                        <div class="room-thumbnail">
                            {% for image in images %}
                            	{% if image.is_main %}
                            		<img src="{{ image.image.url }}" alt>
                            	{% endif %} 
                            {% endfor %}
                            
                        </div>

                        <div class="room-content">
                            <h2>{{ blogs.title }}</h2>
                            <h4>{{ blogs.price }}$ <span>/ Day</span></h4>
                            <div class="room-feature">
                                <h6>Size: <span>{{ blogs.size }} ft</span></h6>
                                <h6>Capacity: <span>Max person {{ blogs.capacity }}</span></h6>
                                <h6>Bed: <span>{{ blogs.bed }}</span></h6>
                                <h6>Services: <span>{% for service in services %}
                                	{{ service.title }}
                                {% endfor %}
                                </span></h6>
                            </div>
                            <a href="{% url 'blog:detail' blogs.slug %}" class="btn view-detail-btn">View Details <i class="fa fa-long-arrow-right"
                                                                                    aria-hidden="true"></i></a>
                        </div>
                    </div>
                    {% endfor %}
                    


                    <nav class="roberto-pagination wow fadeInUp mb-100" data-wow-delay="1000ms">
                        <ul class="pagination">
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"> < Previous <i class="fa fa-angle-left"></i></a>
                            {% endif %}
                        </li>
                        
                        {% for page_number in page_obj.paginator.page_range %}
                        	 <li class="page-item {% if page_obj.number == page_number %}active{% endif %}"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                        {% endfor %}
                        
                           
                        
                            <li class="page-item">
                                {% if page_obj.has_next %}
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next <i class="fa fa-angle-right"></i></a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-12 col-lg-4">

                    <div class="hotel-reservation--area mb-100">
                        <form action="#" method="post">
                            <div class="form-group mb-30">
                                <label for="checkInDate">Date</label>
                                <div class="input-daterange" id="datepicker">
                                    <div class="row no-gutters">
                                        <div class="col-6">
                                            <input type="text" class="input-small form-control" id="checkInDate"
                                                   name="checkInDate" placeholder="Check In">
                                        </div>
                                        <div class="col-6">
                                            <input type="text" class="input-small form-control" name="checkOutDate"
                                                   placeholder="Check Out">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-30">
                                <label for="guests">Guests</label>
                                <div class="row">
                                    <div class="col-6">
                                        <select name="adults" id="guests" class="form-control">
                                            <option value="adults">Adults</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                        </select>
                                    </div>
                                    <div class="col-6">
                                        <select name="children" id="children" class="form-control">
                                            <option value="children">Children</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mb-50">
                                <div class="slider-range">
                                    <div class="range-price">Max Price: $0 - $3000</div>
                                    <div data-min="0" data-max="3000" data-unit="$"
                                         class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"
                                         data-value-min="0" data-value-max="3000" data-label-result="Max Price: ">
                                        <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                                        <span class="ui-slider-handle ui-state-default ui-corner-all"
                                              tabindex="0"></span>
                                        <span class="ui-slider-handle ui-state-default ui-corner-all"
                                              tabindex="0"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn roberto-btn w-100">Check Available</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}